development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: APP_NAME_development
  username: root
  password:
  pool: 5
  timeout: 5000
  # socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: APP_NAME_test
  username: root
  password:
  pool: 5
  timeout: 5000
  # socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: APP_NAME_production
  username: root
  password:
  pool: 5
  timeout: 5000

staging:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: APP_NAME_staging
  username: root
  password:
  pool: 5
  timeout: 5000
